### PR TITLE
Fix games xml to sync with MAME 0.221 ROMs

### PR DESCRIPTION
**Pull request by rtissera**
These games are now playable :
dirtdvls + clones
eca + clones (except ecap => Cabinet Network Error)

### CODE REVIEW

**Comment by njz3** [comment]
Hi,
Sorry, but Emergency Call Ambulance (eca) and Dirt Devils (dirtdvls) shall contain epr-19338a.bin (driveboard EPROM) for forcefeedback. I can confirm this from the real hardware.
See here :
https://hico-srv004.pixhotel.fr/sites/default/files/gamoovernet/20191030170142-BigPanik-E7E552EE-1CF1-4DCB-9EE6-4259324646A0.png
Is this a mistake from MAME 0.221 ?

**Comment by rtissera** [comment]
Hi,

Probably since this rom is not referenced in model3 driver for both games
and clones. Are you in touch with some mame devs ?

**Comment by njz3** [comment]
No, I am not in contact with them.
If you contact them, please send the above link, as it should be corrected in MAME 0.221 rom set.
I will check if the new dumps works ok on supermodel and I can merge only the new dumps. Ok for you?

**Comment by rtissera** [comment]
Sure, let's merge what you can, it's always better than bad dumps laying
out !
I will ping mame devs (it might take some time) and let you know.

**Pull request merged**
